MainWidget:
<MainWidget>:
    Button:
        text: "Click meee"
        size: "200dp", "80dp"
        pos: root.center_x-self.width/2, str(root.center_y-self.height/2-root.center_y/3)+"dp"
        color: 1, 1, 1, 1
        # r g b a
    Label:
        text: "My screen on Kivy"
        font_size: 50
        bold: True
        italic: True
        underline: True
        pos: root.center_x-self.width/2, root.center_y-self.height/2+root.center_y/4
        color: 0.7, 0, 0.7, 0.7
